version: '3.5'
services:
  server:
    image: server:1.0
    container_name: server
    restart: always
    environment:
      - open.ai.token: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
    ports:
      - "9091:9091"


  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - /home/sys-install/config/mysql/data:/var/lib/mysql/:rw
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "19091:19091"
    volumes:
      - /home/sys-install/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/sys-install/config/file:/home/file

  lanproxy:
    image: franklin5/lanproxy-server
    container_name: lanproxy
    restart: always
    environment:
      LANPROXY_USERNAME: root
      LANPROXY_PASSWORD: root
    ports:
      - 8090:8090
      - 4900:4900
      - 4993:4993
      - 9000-9100:9000-9100

  jenkins:
    image: jenkins/jenkins:2.332.3
    container_name: jenkins
    ports:
      - "9000:8080"
    volumes:
      - /home/sys-install/config/jenkins/jenkins_home:/var/jenkins_home
      - /home/jenkins/apache-maven-3.6.3:/home/jenkins/apache-maven-3.6.3
      - /home/jenkins/jdk1.8.0_371:/home/jenkins/jdk1.8.0_371
      - /home/sys-install/config/jenkins/env.sh:/etc/profile.d/env.sh
      #- /home/sys-install/config/jenkins/profile:/etc/profile:rw

